// Starter inventory shown via the empty-state "Load sample set" button.
// A deliberate ROYGBIV spread across a few materials so the shelves look alive.
import type { Spool } from './types';

export const SAMPLE_SPOOLS: Spool[] = [
  // ---- PLA shelf ----
  {
    id: 'seed-pla-red',
    name: 'Lipstick Red',
    manufacturer: 'Prusament',
    type: 'PLA',
    color: { name: 'Lipstick Red', hex: '#c8102e' },
    temps: { nozzleMin: 205, nozzleMax: 215, bed: 60 },
    count: 2,
    diameter: 1.75,
    weightGrams: 1000,
    storage: 'Drybox A',
  },
  {
    id: 'seed-pla-orange',
    name: 'Orange',
    manufacturer: 'Hatchbox',
    type: 'PLA',
    color: { name: 'Orange', hex: '#f15a24' },
    temps: { nozzleMin: 200, nozzleMax: 215, bed: 60 },
    count: 1,
    diameter: 1.75,
    weightGrams: 1000,
  },
  {
    id: 'seed-pla-yellow',
    name: 'PolyTerra Sunflower',
    manufacturer: 'Polymaker',
    type: 'PLA',
    color: { name: 'Sunflower Yellow', hex: '#f4c20d' },
    temps: { nozzleMin: 195, nozzleMax: 210, bed: 55 },
    count: 3,
    diameter: 1.75,
    weightGrams: 1000,
    notes: 'Matte finish, prints great at 210.',
  },
  {
    id: 'seed-pla-green',
    name: 'Pine Green',
    manufacturer: 'eSun',
    type: 'PLA',
    color: { name: 'Pine Green', hex: '#1f8a4c' },
    temps: { nozzleMin: 205, nozzleMax: 220, bed: 60 },
    count: 1,
    diameter: 1.75,
    weightGrams: 1000,
  },
  {
    id: 'seed-pla-blue',
    name: 'Azure Blue',
    manufacturer: 'Prusament',
    type: 'PLA',
    color: { name: 'Azure Blue', hex: '#1f6fd6' },
    temps: { nozzleMin: 205, nozzleMax: 215, bed: 60 },
    count: 2,
    diameter: 1.75,
    weightGrams: 1000,
    purchase: { vendor: 'Prusa', date: '2026-02-14', price: 24.99, currency: 'USD' },
  },
  {
    id: 'seed-pla-violet',
    name: 'Galaxy Purple',
    manufacturer: 'Polymaker',
    type: 'PLA',
    color: { name: 'Galaxy Purple', hex: '#5b2a86' },
    temps: { nozzleMin: 200, nozzleMax: 215, bed: 60 },
    count: 1,
    diameter: 1.75,
    weightGrams: 1000,
  },
  {
    id: 'seed-pla-black',
    name: 'Jet Black',
    manufacturer: 'Prusament',
    type: 'PLA',
    color: { name: 'Jet Black', hex: '#161616' },
    temps: { nozzleMin: 205, nozzleMax: 215, bed: 60 },
    count: 4,
    diameter: 1.75,
    weightGrams: 1000,
    storage: 'Shelf 2',
  },
  {
    id: 'seed-pla-white',
    name: 'Signal White',
    manufacturer: 'Hatchbox',
    type: 'PLA',
    color: { name: 'White', hex: '#f2f2f2' },
    temps: { nozzleMin: 200, nozzleMax: 215, bed: 60 },
    count: 2,
    diameter: 1.75,
    weightGrams: 1000,
  },

  // ---- PETG shelf ----
  {
    id: 'seed-petg-red',
    name: 'Ruby PETG',
    manufacturer: 'Overture',
    type: 'PETG',
    color: { name: 'Ruby Red', hex: '#b3243a' },
    temps: { nozzleMin: 235, nozzleMax: 245, bed: 80 },
    count: 1,
    diameter: 1.75,
    weightGrams: 1000,
  },
  {
    id: 'seed-petg-teal',
    name: 'Solid Teal',
    manufacturer: 'eSun',
    type: 'PETG',
    color: { name: 'Teal', hex: '#0f9d8c' },
    temps: { nozzleMin: 235, nozzleMax: 250, bed: 80 },
    count: 1,
    diameter: 1.75,
    weightGrams: 1000,
  },
  {
    id: 'seed-petg-blue',
    name: 'Transparent Blue',
    manufacturer: 'Sunlu',
    type: 'PETG',
    color: { name: 'Trans Blue', hex: '#2aa0e6' },
    temps: { nozzleMin: 230, nozzleMax: 245, bed: 80 },
    count: 2,
    diameter: 1.75,
    weightGrams: 1000,
  },

  // ---- TPU shelf ----
  {
    id: 'seed-tpu-orange',
    name: 'Fire Orange',
    manufacturer: 'SainSmart',
    type: 'TPU',
    color: { name: 'Fire Orange', hex: '#ef6c1a' },
    temps: { nozzleMin: 215, nozzleMax: 230, bed: 45 },
    count: 1,
    diameter: 1.75,
    weightGrams: 500,
    notes: 'Print slow (~20mm/s).',
  },
  {
    id: 'seed-tpu-black',
    name: 'Stealth Black',
    manufacturer: 'NinjaTek',
    type: 'TPU',
    color: { name: 'Black', hex: '#1a1a1a' },
    temps: { nozzleMin: 220, nozzleMax: 235, bed: 50 },
    count: 1,
    diameter: 1.75,
    weightGrams: 500,
  },
];
